spring.application.name=company-service

server.port=8082


#spring.datasource.url = jdbc:h2:mem:companydb;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;
#spring.h2.console.enabled = true
#spring.jpa.open_in_view = false
#spring.h2.console.path=/h2-console

#postgruesSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/company?TimeZone=Asia/Kolkata
spring.datasource.username=akhi
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#feign
#feign.circuitbreaker.enabled=true

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost


#Zipkin
management.tracing.sampling.probability=1.0
debug=true

#acutator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circutebreakers.enable=true

#CircuteBreaker
resilience4j.circuitbreaker.instances.companyCircuteBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.companyCircuteBreaker.slowCallDurationThreshold=20000
resilience4j.circuitbreaker.instances.companyCircuteBreaker.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.companyCircuteBreaker.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.instances.companyCircuteBreaker.maxWaitDurationInHalfOpenState=10000
resilience4j.circuitbreaker.instances.companyCircuteBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.companyCircuteBreaker.slidingWindowSize=20
resilience4j.circuitbreaker.instances.companyCircuteBreaker.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.companyCircuteBreaker.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.companyCircuteBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
#Better for Production :
#resilience4j.circuitbreaker.instances.companyCircuteBreaker.recordExceptions=
#resilience4j.circuitbreaker.instances.companyCircuteBreaker.ignoreExceptions=
#resilience4j.circuitbreaker.instances.companyCircuteBreaker.recordFailurePredicate=
#resilience4j.circuitbreaker.instances.companyCircuteBreaker.ignoreExceptionPredicate=

#Ratelimiter
resilience4j.ratelimiter.instances.companyCircuteBreaker.timeoutDuration=0
resilience4j.ratelimiter.instances.companyCircuteBreaker.limitRefreshPeriod=4s
resilience4j.ratelimiter.instances.companyCircuteBreaker.limitForPeriod=2