
spring.application.name=eureka

server.port=8761

#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false


# Disable Eureka from trying to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: Set the wait time for peer replication to 0
eureka.server.wait-time-in-ms-when-sync-empty=0