spring.application.name=job-service

server.port=8081

#spring.datasource.url = jdbc:h2:mem:jobdb;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;
#spring.h2.console.enabled = true
#spring.jpa.open_in_view = false
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://localhost:5432/job?TimeZone=Asia/Kolkata
spring.datasource.username=akhi
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost

#eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=127.0.0.1
#instance.localhost

#Zipkin
management.tracing.sampling.probability=1.0
debug=true